---
experiments:
  metero_use: ['2m_temperature',
               'boundary_layer_height',  # Comment out for no_BPL experiments.
               'k_index',
               'relative_humidity+950',
               'surface_pressure',
               'total_precipitation',
               'u_component_of_wind+950',
               'v_component_of_wind+950',]
  save_npy: True
  dataset_num: 1 # or 2
  model: STONE

train:
  batch_size: 32
  epochs: 50
  exp_repeat: 1
  hist_len: 24
  pred_len: 24
  weight_decay: 0.0005
  early_stop: 10
  lr: 0.0005
  new_node_ratio: 0.1 # setting for ood
  c: 3 # setting for frechet

filepath:
  node01: # choose your cuda number
    knowair_fp: ./KnowAir.npy
    results_dir: ./results

data:
  metero_var:
    ['100m_u_component_of_wind',
     '100m_v_component_of_wind',
     '2m_dewpoint_temperature',
     '2m_temperature',
     'boundary_layer_height',
     'k_index',
     'relative_humidity+950',
     'relative_humidity+975',
     'specific_humidity+950',
     'surface_pressure',
     'temperature+925',
     'temperature+950',
     'total_precipitation',
     'u_component_of_wind+950',
     'v_component_of_wind+950',
     'vertical_velocity+950',
     'vorticity+950']

dataset:
  data_start: [[2015, 1, 1, 0, 0], GMT]
  data_end: [[2018, 12, 31, 21, 0], GMT]

  1: # setting like STONE
    train_start: [[2017, 1, 1], GMT]
    train_end: [[2017, 8, 31], GMT]
    val_start: [[2017, 9, 1], GMT]
    val_end: [[2017, 10, 31], GMT]
    test_start: [[2018, 11, 1], GMT]
    test_end: [[2018, 12, 31], GMT]

  2: # setting like STONE
    train_start: [[2015, 1, 1], GMT]
    train_end: [[2015, 8, 31], GMT]
    val_start: [[2015, 9, 1], GMT]
    val_end: [[2015, 10, 31], GMT]
    test_start: [[2016, 11, 1], GMT]
    test_end: [[2016, 12, 31], GMT]

# patameters of STONE
STONE:
  Kt: 3
  Ks_s: 1
  Ks_t: 1
  dropout: 0.5
  adp_s_dim: 16
  adp_t_dim: 16
  x_output_dim: 64
  sem_output_dim: 64
  gate_output_dim: 64
